### PR TITLE
Add posibility to activate ipr systemd units via udev rule

### PR DESCRIPTION
**Pull request by jcajka**
Makes possible to have ipr deamons started via udev rule that triggers general iprutils.target starting all of the daemons.  Also all new files are added to the dist archive.

This patch has been carried for a while(3y) in the Fedora and seems to work without any issues.

cc @sharkcz

### CODE REVIEW

**Comment by sharkcz** [comment]
Also the udev activation means that the daemons are started only when an IPR adapter is present in the system.

**Comment by jcajka** [comment]
@sharkcz thanks for the improvements, addition of the proper installation bits

**Comment by bjking1** [comment]
@jcajka and @sharkcz thanks for the change! I made a couple minor tweaks on top of it to get it to work for me as well as integration with the rpm spec file. Please let me know if I broke anything in your setup.

**Comment by sharkcz** [comment]
it looks good, thanks for merging

**Pull request merged**
